"""Second migration

Revision ID: a1ac2cd64391
Revises: 9ad908d50f6d
Create Date: 2024-11-13 13:22:06.393897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ac2cd64391'
down_revision = '9ad908d50f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
